version: '3'

services:
    php73:
        image: php:7.3-apache
        ports:
          - 8081:80
        volumes:
            - C:\Users\luis.olivetti\Documents\GitHub\CommandPattern:/var/www/html/